export const mockMpt = [{
    client_order_id: '',
    order_date: '',
    order_need_by_date: '',
    po_id: '',
    sent_to_print_date: '',
    customer_product_id: '',
    kit_y_n: '',
    li_id: '',
    status: '',
    lic_id: '',
    component_number: '',
    customer_sku: '',
    lic_quantity: '',
    print_vendor: '',
    p3Segment: '',
    userName: '',
    trim_sku: '',
    productName: '',
    productType: '',
    oecb_identifier: '',
    placemat_identifier: '',
    bensum_identifier: '',
    tracking_number: ''
}, {
    client_order_id: '2000002639',
    order_date: '2020-12-13 21:53:07',
    order_need_by_date: '2020-12-24 00:00:00',
    po_id: '7263',
    sent_to_print_date: '2020-12-13',
    customer_product_id: 'Accident Protection Plan OE flier - Platinum',
    kit_y_n: '',
    li_id: '9395',
    status: 'IN_PROCESS',
    lic_id: '13824',
    component_number: '6464',
    customer_sku: 'MT-1148760.0',
    lic_quantity: '100',
    print_vendor: 'Shutterfly Inc',
    p3Segment: 'Small Business',
    userName: 'v-swati.goel@shutterfly.com',
    trim_sku: 'MT-1148760',
    productName: 'Accident Protection Plan OE flier - Platinum',
    productType: 'static',
    oecb_identifier: 'accident protection plan oe flier - platinum',
    placemat_identifier: 'static',
    bensum_identifier: '',
    tracking_number: ''
}]