server:
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: eni-reports
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 3600000
  flyway:
    check-location: true
    enabled: true
    locations: classpath:db/migration
    sql-migration-prefix: v
    sql-migration-suffixes: .sql
    outOfOrder: true
    baseline-on-migrate: true
    validateOnMigrate: false
    table: schema_version_reports
  mvc:
    view:
      suffix: .html
app:
  base-url: http://localhost:8081
  security:
    auth:
      access-token-cookie-max-age: 1800
      cookie-domain: internal.shutterfly.com
      app-code: eni
      client-id: sbs-eni-client
      client-secret: secret
      gateway-endpoint: http://dsbsapp84-lv.internal.shutterfly.com:8080
      refresh-token-cookie-max-age: 86400
      issuer: http://dsbsapp94-lv.internal.shutterfly.com:7000
  ui:
    auth:
      customer-base-endpoint: ${app.security.auth.gateway-endpoint}
      customer-web-endpoint: ${app.base-url}
      log-ui-error: ${app.base-url}/api/log
    reports:
      customer-base-endpoint: ${app.security.auth.gateway-endpoint}
      customer-web-endpoint: ${app.base-url}
      log-ui-error: ${app.base-url}/api/log
      login-url: ${app.login-url}
      access-role: eni_ADMIN
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/EnI?serverTimezone=UTC
    username: root
    password: Password@123
app:
  base-url: http://localhost:8081
  security:
    auth:
      gateway-endpoint: http://dsbsapp84-lv.internal.shutterfly.com:8080
      cookie-domain: internal.shutterfly.com
logging:
  level:
    root: debug

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://dsbssql01-lv.internal.shutterfly.com:3306/EnI?serverTimezone=UTC
    username: sbs_eni_svc
    password: sbs_eni_svc
  flyway:
    placeholders:
      schema: EnI
app:
  base-url: http://dsbsapp107-lv.internal.shutterfly.com:8081
  login-url: http://dsbsapp107-lv.internal.shutterfly.com:8080/auth
  security:
    auth:
      gateway-endpoint: http://dsbsapp84-lv.internal.shutterfly.com:8080
      cookie-domain: internal.shutterfly.com
---
spring:
  profiles: qa
  datasource:
    url: jdbc:mysql://tsbssql01-lv.internal.shutterfly.com:3306/EnI?serverTimezone=UTC
    username: sbs_eni_svc
    password: sbs_eni_svc
  flyway:
    placeholders:
      schema: EnI
app:
  base-url: http://eni-reports-qa.internal.shutterfly.com
  login-url: http://eni-pop-qa.internal.shutterfly.com/auth
  security:
    auth:
      gateway-endpoint: https://tsbsapp109-lv.internal.shutterfly.com:8443
      cookie-domain: internal.shutterfly.com
      issuer: http://tsbsapp124-lv.internal.shutterfly.com:7000
---
spring:
  profiles: stage
  datasource:
    url: jdbc:mysql://xuhgsql15-lv/eni?verifyServerCertificate=false&useSSL=true&requireSSL=false&rewriteBatchedStatements=true
    username: sbs_stg_eni
    password: KGFfc6VA
  flyway:
    placeholders:
      schema: sbs_platform_order
app:
  base-url: https://eni-reports-stage.sbs.shutterfly.com
  login-url: https://eni-pop-stage.sbs.shutterfly.com/auth
  security:
    auth:
      gateway-endpoint: https://web-api-uhg-stage.sbs.shutterfly.com
      cookie-domain: sbs.shutterfly.com
      issuer: https://auth-api-uhg-stage.internal.shutterfly.com
server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto