server:
  port: 8081
spring:
  application:
    name: eni-reports
  mvc:
    view:
      suffix: .html
app:
  base-url: http://localhost:8081
  security:
    auth:
      access-token-cookie-max-age: 1800
      cookie-domain: internal.shutterfly.com
      app-code: eni
      client-id: sbs-eni-client
      client-secret: secret
      gateway-endpoint: http://dsbsapp84-lv.internal.shutterfly.com:8080
      refresh-token-cookie-max-age: 86400
      issuer: http://dsbsapp94-lv.internal.shutterfly.com:7000
  ui:
    auth:
      customer-base-endpoint: ${app.security.auth.gateway-endpoint}
      customer-web-endpoint: ${app.base-url}
      log-ui-error: ${app.base-url}/api/log
---
spring:
  profiles: local
app:
  base-url: http://localhost:8081
  security:
    auth:
      gateway-endpoint: http://dsbsapp84-lv.internal.shutterfly.com:8080
      cookie-domain: internal.shutterfly.com
logging:
  level:
    root: debug

---
spring:
  profiles: dev
app:
  base-url: http://dsbsapp107-lv.internal.shutterfly.com:8081
  security:
    auth:
      gateway-endpoint: http://dsbsapp84-lv.internal.shutterfly.com:8080
      cookie-domain: internal.shutterfly.com
